const categories = [
    "car",
    "transport",
    "groceries",
    "home",
    "food",
    "friends",
    "pet",
    "housing",
    "boyfriend",
    "girlfriend",
    "family",
    "Luxuries",
    "bills",
    "utilities",
    "insurance",
    "phone",
    "internet",
    "subscriptions",
    "entertainment",
    "health",
    "eating out",
    "clothing",
    "education",
    "travel",
    "gifts",
    "savings",
    "investments",
    "other",
];

module.exports = categories;